---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggNaruto

<!-- badges: start -->
<!-- badges: end -->

The goal of ggNaruto is to provide Colour palettes inspired by Naruto.

## Installation

You can install the released version of ggNaruto from [github](https://github.com/NotebookOFXiaoMing/ggNaruto) with:

``` r
devtools::install_github("NotebookOFXiaoMing/ggNaruto")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(ggplot2)
library(ggNaruto)
library(cowplot)
help(package="ggNaruto")
naruto_palette("Jiraiya")
naruto_palettes

dat01<-data.frame(x=LETTERS[1:8],y=1:8)
ggplot(data=dat01,aes(x=x,y=y))+
  geom_col(aes(fill=x))+
  scale_fill_naruto_d(name = "Team7")+
  theme_bw() -> my_plot

team7<-system.file("extdata",'team7.png',package = "ggNaruto")
team7
ggdraw() +
  draw_image(team7) -> p2

plot_grid(my_plot,p2)
```


